### ISSUE TITLE
Preparation for classification

### ISSUE THREAD

**Issue by nehorg** [JonMuehlst/pcap-feature-extractor#9]
By evaluating the metadata in the destination mac address the system should:
1. Discard non-relevant pcaps (with metadata  that is used by "Flash").
2. Use the relevant model for the appropriate time window.

**Comment by yzion** [comment]
@erlichsefi 

> @yzion , where are the pkls for all the other classifier?

You need to run the "learn part" again for each data-set and save the classifier into pkl.

> @yzion and do you save the feature list in the configuration file? 

Yes, you can change the feature list in the hcl configuration file

> that means that all features are the same for all classifiers?
in: https://github.com/nehorg/Simulator/blob/1e5f6dd81750892d2b4dc0b6d9fd3af4464ff5ac/pcap-feature-extractor/network_wordcount.py#L173

And yes, the features are the same for all samples type.

**Comment by erlichsefi** [comment]
done, we only need to decide from where to read the mac

**Comment by erlichsefi** [comment]
closing, currently read the true label Mac from the first packet
